server:
  port: 8088
spring:
  datasource:
    name: kpmanage
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: zljg
    password: zljg123456
    driverClassName: oracle.jdbc.driver.OracleDriver
    initialSize: 5  #初始建立连接数量
    minIdle: 5  #最小连接数量
    maxActive: 20 #最大连接数量
    maxWait: 10000  #获取连接最大等待时间，毫秒
    testOnBorrow: true #申请连接时检测连接是否有效
    testOnReturn: false #归还连接时检测连接是否有效
    timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
    minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
